### ISSUE TITLE
I can't type the username or email, the keyboard doesn't popup up when I focus on the first input

### ISSUE THREAD

**Issue by LastStranger** [Nyabsi/VRCAA#16]
and the password input is working, the keyboard popups up as normal

**Comment by Nyabsi** [comment]
That is infact known bug which is caused by the Compose framework, unfortunately I don't believe I can fix it, but I can look into potential workaround solutions

**Comment by Nyabsi** [comment]
Hey, @LastStranger I pushed new commit that should fix the issue you were experiencing, can you download latest version and report the results?

**Comment by LastStranger** [comment]
> Hey, @LastStranger I pushed new commit that should fix the issue you were experiencing, can you download latest version and report the results?

it works well, I've logged in to this app

**Comment by LastStranger** [comment]
by the way, I looked the resource codes, I found some codes seems related to i18n, does that means I can switch to another language in this app? how do i do that?

**Comment by Nyabsi** [comment]
It's based on your operating system language, if you change the language of your system, it should automatically switch to translated version, but there is only few languages translated: Finnish, Japanese, German and Dutch

**Comment by LastStranger** [comment]
I see, really cool project

**Comment by Nyabsi** [comment]
Thanks, I did see you were working on something similar so if you got any questions you can contact me at veenixr in discord btw 👍🏻

**Comment by LastStranger** [comment]
hhh, I will
