### ISSUE TITLE
Discord invite invalid 

### ISSUE THREAD

**Issue by BlackWolfWoof** [Nyabsi/VRCAA#47]
The discord invite in the readme seems to be invalid.

**Comment by Nyabsi** [comment]
Hey,

I recently updated the link and it works for me.

But here: https://discord.com/invite/CXd4nDmX

**Comment by BlackWolfWoof** [comment]
Skill issue on my side which was caused by a ratelimit from discord. Welp, thanks discord for not saying "you are ratelimited lol" when clicking the invite and instead saying it is invalid
