### ISSUE TITLE
Mark nighties as pre-release

### ISSUE THREAD

**Issue by Anti-Apple4life** [Nyabsi/VRCAA#62]
Would it be possible to mark the nightly builds as pre-release, so people can use apps like Obtanium to get the latest stable version and not the nightly?

**Comment by Nyabsi** [comment]
Stable versions are only released through F-Droid, I do not distrubute stable versions through Github.

**Comment by Nyabsi** [comment]
as side note; Obtanium supports F-Droid as source of applications, pleaee use that instead.
